### ISSUE TITLE
Remove 'Reserve ticket' option

### ISSUE THREAD

**Issue by jeroentjuuhh** [WISVCH/events#286]
Currently, people are able to reserve tickets, but this causes some problems. For example, the board does not always know the exact amount of people that will attend. Money wise, it also gives some problems. We have so many ways you can now buy your tickets, which makes it very hard for the treasurer to keep track where the money came from.

I would suggest one of the following three options;
- Delete it (maybe for now only front end)
- Let the creator of the event decide whether they would like to have the reserved option.
- Make the reserved tickets expire 1 or 2 days in advance and send them a reminder to pay for their tickets.

It would be helpfull if one of those (or a better one) would be implemented.

**Comment by svenpopping** [comment]
Completely removing or disabling this 'payment' method is not an option. Since it is legally required to have a 'betaal achteraf' option and secondly based you do not want to force the customer to pay the transaction cost. Meaning option one and two are not an option.

So this means that the remainder is the third options. It enables the 'betaal achteraf' method and one or two days before you know the number of people that will attend.

**Comment by Fastjur** [comment]
It seems that, while this is true, there are exceptions to this rule.

> Ondanks dat iDEAL ontzettend veel gebruikt wordt in Nederland en goed ingeburgerd is, betekent dit dat je verplicht bent om minimaal één achteraf-betaalmogelijkheid aan te bieden in je webwinkel. Deze regel geldt overigens alleen als je je op consumenten richt en als je producten verkoopt. Voor zakelijke klanten en diensten geldt deze wet niet en kun je zelf bepalen hoe en wanneer je je geld wilt ontvangen.

We do not offer products, but services and events. As such we are not obliged to have such an option. I would recommend we still implement this, using option 2: Let the creator of the event decide whether they would like to have the reserved option.
With the default being 'on'. This would tremendously help us for certain events.
